<a href="https://colab.research.google.com/github/minhasaleem/Deep-Vision-AI-Workshop/blob/main/Day_2_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,28,9]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 28  9]]


In [ ]:
print(a[:, 0])

[1 4 7]


In [ ]:
print(a[2,:])

[ 7 28  9]


In [ ]:
print(a[1,1])

5


In [ ]:
print(a[1,0])

4


In [ ]:
print(np.diag(a))

[1 5 9]


In [ ]:
a[a % 2 == 0] = 0
print(a)

[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [ ]:
print(a[::-1])

[[7 0 9]
 [0 5 0]
 [1 0 3]]


In [ ]:
print(a.shape)

(3, 3)


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.size)

9


In [ ]:
print(np.sum(a))

25


In [ ]:
print(np.mean(a))

2.7777777777777777


In [ ]:
print(np.max(a))

9


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
b = a.reshape(6, 4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
c = a.reshape(2, 3, 4)
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
random=np.arange(0,20,1)
print(random)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print("Mean:", np.mean(a))

Mean: 12.5


In [ ]:
print("Median:", np.median(a))

Median: 12.5


In [ ]:
print("Standard Deviation:", np.std(a))

Standard Deviation: 6.922186552431729


In [ ]:
print(a[a > 50])

[]


In [ ]:
a[a < 50] = 50
print(a)

[50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
sum=a+b
print(sum)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
diff=a-b
print(diff)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
product=a*b
print(product)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
